version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: africa2035-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./output:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80