[project]
name = "africa2035"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "invoke>=2.2.0",
    "livereload>=2.7.1",
    "pelican[markdown]>=4.11.0",
]
